# Cloud Build configuration for Vision Inference API deployment to Cloud Run
steps:
  # Step 1: Build and push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${BUILD_ID}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '-f'
      - 'ModelDevelopment/VisionInference/Dockerfile'
      - 'ModelDevelopment/VisionInference'
    dir: '.'  # Build from workspace root

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    waitFor: ['build-image']
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    waitFor: ['push-image']
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5000'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'USE_GCS_MODELS=true,GCS_BUCKET_NAME=medscan-pipeline-medscanai-476500,GCS_MODELS_PREFIX=vision/trained_models'
    env:
      - 'CLOUDSDK_RUN_PLATFORM=managed'

# Build configuration
timeout: 1800s  # 30 minutes

substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'vision-inference-api'
  _IMAGE_NAME: 'vision-inference'
  _REPO_NAME: 'vision-inference'
  _MEMORY: '2Gi'
  _CPU: '1'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '3'

options:
  logging: CLOUD_LOGGING_ONLY
