# TFDV and MLMD Configuration for MedScan AI

# Dataset Configuration
datasets:
  tb:
    name: "tb_patients"
    raw_base_path: "data/raw/tb"
    preprocessed_base_path: "data/preprocessed/tb"
    metadata_base_path: "data/synthetic_metadata/tb"  # Disease-specific metadata path
    metadata_filename: "tb_patients.csv"
    description: "Tuberculosis chest X-ray patient metadata"
  
  lung_cancer:
    name: "lung_cancer_ct_scan_patients"
    raw_base_path: "data/raw/lung_cancer"
    preprocessed_base_path: "data/preprocessed/lung_cancer"
    metadata_base_path: "data/synthetic_metadata/lung_cancer"  # Disease-specific metadata path
    metadata_filename: "lung_cancer_ct_scan_patients.csv"
    description: "Lung cancer CT scan patient metadata"

# Partitioning Configuration
partitioning:
  enabled: true
  format: "year/month/day"  # Directory structure: YYYY/MM/DD
  metadata_file: "data/partition_metadata.json"  # Tracks raw->preprocessed mappings

# Schema Constraints
schema_constraints:
  numerical_features:
    Age_Years:
      min: 0
      max: 120
      required: true
    
    Weight_KG:
      min: 2
      max: 300
      required: true
    
    Height_CM:
      min: 40
      max: 250
      required: true
  
  categorical_features:
    Gender:
      allowed_values: ["Male", "Female", "Other"]
      required: true
    
    Examination_Type:
      allowed_values: ["X-ray", "CT", "MRI", "Ultrasound", "PET", "Mammography"]
      required: true
    
    Body_Region:
      allowed_values: ["Head", "Chest", "Abdomen", "Pelvis", "Spine", "Extremities", "Head/Brain"]
      required: true
    
    Urgency_Level:
      allowed_values: ["Routine", "Urgent", "Emergent", "STAT"]
      required: true
    
    Diagnosis_Class:
      required: true
      # Values are dataset-specific: Normal, Tuberculosis for tb
      # adenocarcinoma, large.cell.carcinoma, normal, squamous.cell.carcinoma for lung
  
  string_features:
    Patient_Full_Name:
      required: true
    
    Patient_ID:
      required: true
      unique: true
    
    Presenting_Symptoms:
      required: false
    
    Current_Medications:
      required: false
    
    Previous_Relevant_Surgeries:
      required: false
    
    Image_Path:
      required: true

# Great Expectations Configuration
great_expectations:
  statistics:
    # Output directories for statistics
    output_dir: "data/ge_outputs"
    baseline_dir: "data/ge_outputs/baseline"
    new_data_dir: "data/ge_outputs/new_data"
    
    # Statistics generation options
    feature_allowlist: null  # null means all features
    schema_inference:
      infer_feature_shape: true
      max_string_domain_size: 100
  
  schema:
    # Schema output directory
    output_dir: "data/ge_outputs/schemas"
    
    # Schema customization
    auto_infer: true
    
  validation:
    # Validation output directory
    output_dir: "data/ge_outputs/validations"
    
    # Anomaly detection thresholds
    enable_anomaly_detection: true
    
  drift_detection:
    # Drift detection configuration
    enable: true
    output_dir: "data/ge_outputs/drift"
    
    # Statistical test threshold for drift detection
    statistical_test_threshold: 0.00001  # P-value threshold (lower = more sensitive)
    
  visualization:
    # HTML report generation
    enable: true
    output_dir: "data/ge_outputs/reports"
    statistics_report: "statistics_report.html"
    schema_report: "schema_report.html"
    validation_report: "validation_report.html"
    drift_report: "drift_report.html"

# Exploratory Data Analysis (EDA) Configuration
eda:
  # EDA output directory
  output_dir: "data/ge_outputs/eda"
  
  # EDA options
  enable: true
  outlier_detection_method: "IQR"  # IQR (Interquartile Range) or Z-score
  correlation_threshold: 0.5  # Threshold for high correlations
  histogram_bins: 20  # Number of bins for histograms

# Advanced Data Bias Detection Configuration
bias_detection:
  # Bias detection output directory
  output_dir: "data/ge_outputs/bias_analysis"
  
  # Enable bias detection
  enable: true
  
  # Advanced bias detection libraries
  libraries:
    # Custom SliceFinder implementation for automatic problematic slice discovery
    slicefinder:
      enable: true
      min_slice_size: 30
      max_slices: 50
      alpha: 0.05  # Significance level
      max_problematic_slices: 10
      distribution_threshold: 0.1  # 10% deviation threshold
      missing_data_threshold: 0.05  # 5% missing data difference threshold
      z_score_threshold: 2.0  # Z-score threshold for numerical anomalies
    
    # TensorFlow Model Analysis for comprehensive model performance slicing
    tfma:
      enable: true
      model_type: "RandomForestClassifier"
      performance_threshold: 0.2  # 20% performance difference threshold
      min_slice_size: 10
    
    # Enhanced Fairlearn for industry-standard fairness metrics
    fairlearn:
      enable: true
      demographic_parity_threshold: 0.1  # 10% difference threshold
      equalized_odds_threshold: 0.1     # 10% difference threshold
      ratio_threshold: 0.8               # 80% rule threshold
  
  # Slicing features for bias analysis
  slicing_features:
    - "Age_Years"
    - "Age_Group"
    - "Diagnosis_Class"
    - "Urgency_Level"
    - "Body_Region"
  
  # Age grouping for age-based slicing
  age_bins:
    - name: "Young Adult"
      min: 18
      max: 35
    - name: "Middle Age"
      min: 36
      max: 55
    - name: "Senior"
      min: 56
      max: 75
    - name: "Elderly"
      min: 76
      max: 120
  
  # Statistical tests for bias detection (legacy support)
  statistical_tests:
    # Chi-square test for categorical distributions
    chi_square_threshold: 0.05  # P-value threshold for significance
    
    # Cohen's d effect size threshold (0.2=small, 0.5=medium, 0.8=large)
    effect_size_threshold: 0.3
    
    # Minimum sample size per slice to be considered valid
    min_slice_size: 30
  
  # Advanced bias mitigation strategies
  mitigation:
    enable: true
    
    # Output directory for mitigated datasets (partitioned by date: YYYY/MM/DD)
    mitigated_data_output_dir: "data/synthetic_metadata_mitigated"
    
    # Strategies to apply when bias is detected
    strategies:
      - "resample_underrepresented"  # Over-sample minority groups
      - "class_weights"  # Compute class weights for model training
      - "stratified_split"  # Ensure proportional representation
      - "fairlearn_postprocessing"  # Use Fairlearn ThresholdOptimizer
      - "correlation_removal"  # Use Fairlearn CorrelationRemover
    
    # Resampling configuration
    resampling:
      target_ratio: 0.8  # Target ratio for balanced groups (0.8 = 80%)
      method: "balanced"  # balanced, oversample, undersample, or smote
    
    # Fairlearn post-processing configuration
    fairlearn_postprocessing:
      threshold_optimizer:
        enable: true
        objective: "demographic_parity"  # or "equalized_odds"
        threshold_range: [0.1, 0.9]
      
      correlation_remover:
        enable: true
        sensitive_feature_names: ["Age_Group"]
    
    # Document mitigation process
    generate_report: true
  
  # Comprehensive fairness metrics to compute
  fairness_metrics:
    # Demographic Parity
    demographic_parity:
      enable: true
      difference_threshold: 0.1
      ratio_threshold: 0.8
    
    # Equalized Odds
    equalized_odds:
      enable: true
      difference_threshold: 0.1
      ratio_threshold: 0.8
    
    # Equal Opportunity
    equal_opportunity:
      enable: true
      difference_threshold: 0.1
      ratio_threshold: 0.8
    
    # Calibration
    calibration:
      enable: true
      difference_threshold: 0.1

# MLMD Configuration (used by MLflow)
mlmd:
  # Metadata store configuration
  store:
    type: "sqlite"  # sqlite or mysql
    database_path: "/tmp/mlflow/metadata.db"
    
  # Artifact types
  artifact_types:
    - name: "Dataset"
      properties:
        - name: "name"
          type: "STRING"
        - name: "path"
          type: "STRING"
        - name: "num_rows"
          type: "INT"
        - name: "num_columns"
          type: "INT"
        - name: "description"
          type: "STRING"
    
    - name: "Schema"
      properties:
        - name: "name"
          type: "STRING"
        - name: "path"
          type: "STRING"
        - name: "num_features"
          type: "INT"
        - name: "version"
          type: "STRING"
    
    - name: "Statistics"
      properties:
        - name: "name"
          type: "STRING"
        - name: "path"
          type: "STRING"
        - name: "dataset_name"
          type: "STRING"
        - name: "num_examples"
          type: "INT"
    
    - name: "ValidationResult"
      properties:
        - name: "name"
          type: "STRING"
        - name: "path"
          type: "STRING"
        - name: "is_valid"
          type: "INT"
        - name: "num_anomalies"
          type: "INT"
        - name: "dataset_name"
          type: "STRING"
    
    - name: "DriftReport"
      properties:
        - name: "name"
          type: "STRING"
        - name: "path"
          type: "STRING"
        - name: "baseline_dataset"
          type: "STRING"
        - name: "comparison_dataset"
          type: "STRING"
        - name: "has_drift"
          type: "INT"
  
  # Execution types
  execution_types:
    - name: "StatisticsGeneration"
      properties:
        - name: "dataset_name"
          type: "STRING"
        - name: "timestamp"
          type: "STRING"
        - name: "num_examples"
          type: "INT"
    
    - name: "SchemaInference"
      properties:
        - name: "dataset_name"
          type: "STRING"
        - name: "timestamp"
          type: "STRING"
        - name: "num_features"
          type: "INT"
    
    - name: "DataValidation"
      properties:
        - name: "dataset_name"
          type: "STRING"
        - name: "timestamp"
          type: "STRING"
        - name: "is_valid"
          type: "INT"
        - name: "num_anomalies"
          type: "INT"
    
    - name: "DriftDetection"
      properties:
        - name: "baseline_dataset"
          type: "STRING"
        - name: "comparison_dataset"
          type: "STRING"
        - name: "timestamp"
          type: "STRING"
        - name: "has_drift"
          type: "INT"
  
  # Context types
  context_types:
    - name: "DataValidationPipeline"
      properties:
        - name: "pipeline_name"
          type: "STRING"
        - name: "version"
          type: "STRING"

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "data/logs/schema_statistics.log"

# Execution Configuration
execution:
  # Which datasets to process
  process_datasets:
    - "tb"
    - "lung_cancer"
  
  # Which operations to perform
  operations:
    generate_statistics: true
    infer_schema: true
    perform_eda: true  # Perform exploratory data analysis on latest partition
    validate_data: true
    detect_drift: true
    detect_bias: true  # Perform bias detection using data slicing
    generate_reports: true
  
  # Drift detection setup
  drift:
    # Use temporal partitions for drift detection
    enabled: true
    min_partitions_required: 2  # Need at least 2 partitions to detect drift
    baseline_partition: "second_most_recent"  # Use second most recent partition as baseline
    new_partition: "most_recent"  # Use most recent partition as new data

# MLflow Tracking Configuration
mlflow:
  # MLflow tracking URI (MUST be writable path)
  tracking_uri: "file:///tmp/mlflow/metadata/mlruns"
  
  # Experiment name
  experiment_name: "MedScan_Data_Validation"
  
  # Enable MLflow tracking
  enable: true
  
  # Log artifacts to MLflow
  log_artifacts: true
  
  # Artifact location
  artifact_location: "/tmp/mlflow/metadata/artifacts"
  
  # What to log
  log_params: true
  log_metrics: true
  log_artifacts: true
  
  # Auto-log configuration
  autolog:
    enable: true
    log_models: false  # We're not training models here
    log_input_examples: false
    log_model_signatures: false